= Prime numbers checker

How to run this app:

[source,powershell]
----
mvn package
java -jar .\target\sdc-exercise-1.0-SNAPSHOT-jar-with-dependencies.jar -- '.\vzorek_dat - kopie.xlsx'
----

This app is built using Java 25 and Maven 3.9.11.
VS Code has been used as a code editor, with the https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack[Extension Pack for Java] extension.

== Misc.

VisualIndex = the index that is shown by spreadsheet's UI, it is 1-based.

== What input file is expected

== Multithreaded architecture

Main thread reads values from the Excel file, and puts them in a queue.

Then multiple worker threads, represented by the `PrimalityChecker` class,
are picking the values, and are processing them.
That works.

But then we need to reorder them back. That's to be done yet.

== Decisions made during development

=== Which Excel library should I use?

This https://www.baeldung.com/java-microsoft-excel[Baeldung article] mentions three -- Apache POI, JExcel and Fastexcel.
Since I only need to _read_ `*.xlsx` files, JExcel is out -- it only supports older `*.xls` files.
Fastexcel is developed with emphasis on quick generation of files, but in general supports less `*.xlsx`-related features.

My bottleneck will most likely be the prime check, not the reading (that will happen only once) -- so I'll pick Apache POI,
as it seems to be the most versatile tool -- in case I'd need to do anything else Excel-related in future, this seems to be
pretty likely to support it.

=== How to approach logging?

The instructions say that I should use `Logger`.
I'll use Log4j, since:

* I'm used to work with it;
* Apache POI does already use it
* It does implement a [`Logger`]https://logging.apache.org/log4j/2.x/javadoc/log4j-api/org/apache/logging/log4j/Logger.html class.

I don't like the explicit `LogManager.getLogger()` stuff -- so this is the perfect time to also introduce Lombok.

=== How to test the standard output?

The app is supposed to give output via stdout using a Logger.
This makes it tricky to test -- jUnit nor logging frameworks seem to have any
significant support for testing the logged messages.

Only exception is `OutputCaptureExtension` from Spring Boot... but I'd like to
avoid introducing Spring Boot here.

Well, after spending too much time on this, I'm moving on, perhaps solving this later.

=== Is the first row allways gonna contain 'Data' string?

It's not specified by the assignment.
So I'll treat it as ordinary data cell, that may contain valid data.

== Sources used

=== AKS implementation

Has been obtained from https://github.com/smanikar/primality-testing/blob/master/src/aks-final/AKS.java[smanikar/primality-testing].

=== Informational sources

* https://jdk.java.net/25/
* https://maven.apache.org/download.cgi
* https://github.com/junit-team/junit-examples/blob/r6.0.0/junit-jupiter-starter-maven/pom.xml
* https://central.sonatype.com
* https://www.baeldung.com/java-jar-executable-manifest-main-class#1-using-maven
* https://www.baeldung.com/java-microsoft-excel
* https://github.com/dhatim/fastexcel
* https://github.com/apache/poi
* https://poi.apache.org/
* https://poi.apache.org/apidocs/5.0/
* https://www.baeldung.com/java-try-with-
* https://www.baeldung.com/executable-jar-with-maven
* https://logging.apache.org/log4j/2.x/manual/installation.html
* https://projectlombok.org/setup/maven
* https://logging.apache.org/log4j/2.x/manual/getting-started.html
* https://stackoverflow.com/a/16699049/9556542
* https://commons.apache.org/proper/commons-lang/
* https://en.wikipedia.org/wiki/Primality_test
* https://en.wikipedia.org/wiki/AKS_primality_test
* https://stackoverflow.com/questions/4009198/java-get-greatest-common-divisor
* https://youtu.be/rQ7BzfRz7OY?si=0xRl9nzpCdA8v6xn
* https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
* https://stackoverflow.com/a/4759606/9556542